squint-cljs/squint

- src/clava/compiler.cljc
- test/clava/compiler_test.cljs
> Fix namespaced keywords used as keys

- core.js
- test/clava/compiler_test.cljs
> get corner case

- README.md
> Fix Clojure/JSX syntax in readme

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> [feat #51] interleave

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> [feat #105] - merge

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> [feat #77] partition-all

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> [feat #108] into

- core.js
- test/clava/compiler_test.cljs
> `merge` corner cases

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
-------
---
Implements `satisfies?`. Related #126
> satisfies?

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
-------
---
Implements `comp`.
> implement comp

- core.js
- test/clava/compiler_test.cljs
> implement vec

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> implement last

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> implement lazy cons

- core.js
- test/clava/compiler_test.cljs
> Lazy concat

- core.js
- test/clava/compiler_test.cljs
> Lazy interleave

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> implement set

- core.js
- test/clava/compiler_test.cljs
> lazy partition, partition-all

- core.js
This seems to have best overall performance
> simplify plus

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> every?, fixes #68

- core.js
- test/clava/compiler_test.cljs
> Eager mapv

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> drop-last and butlast

- core.js
- resources/clava/core.edn
- test/clava/compiler_test.cljs
> split-at, split-with

- deps.edn
> Bump common

- CHANGELOG.md
- core.js
- test/squint/compiler_test.cljs
> Fix undefined keys/values when passing objects and maps to conj

- CHANGELOG.md
- core.js
- test/squint/compiler_test.cljs
> make dissoc work with multiple keys

- README.md
- Also added Cherry emoji
- [ 🙅‍♂️ ] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
- [ 🙅‍♂️ ] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions
- [ 🙅‍♂️ ] I have updated the [CHANGELOG.md](https://github.com/squint-cljs/squint/blob/master/CHANGELOG.md) file with a description of the addressed issue.
> Fix typo ✏️

- core.js
- resources/squint/core.edn
- src/squint/compiler.cljc
- src/squint/compiler_common.cljc
- src/squint/internal/macros.cljc
- test/squint/compiler_test.cljs
---
Closes #245. Implements `for` very similarly to #293
> implement for & tests

- resources/squint/core.edn
- src/squint/core.js
> Add NaN? predicate

- src/squint/repl/nrepl_server.cljs
* honoring common cider/pprint options
It's basically a copy of how this is done in the [Joyride](https://github.com/BetterThanTomorrow/joyride) nrepl server.
Not yet. I tried, but couldn't figure out how to make the test run.
> Send nrepl results using pprint

- CHANGELOG.md
- index.html
And also some sharing instructions as a tooltip, like with cherry. Actually, I copied the structure from cherry, so that's why the diff looks a bit much. 
> Add playground button for creating blank aoc playground

- CHANGELOG.md
- src/squint/set.js
- test/squint/compiler_test.cljs
> Add more `clojure.set` functions: `difference`, `union`, `subset?`, and `superset?`

- CHANGELOG.md
- src/squint/set.js
- test/squint/compiler_test.cljs
> Add `clojure.set/select`

- examples/vite-react/README.md
This is a minor documentation change.
> Added index.cljs to vite example README.

- CHANGELOG.md
- src/squint/core.js
> [!NOTE]
> I did not add an extra test as testing performances and randomness distribution seems out of the scope of unit tests
I've changed the `left` variable name to `remaining` as to avoid confusing with `left` / `right` and make it a bit easier to read, open to any other feedback.
> Fix #513: Improve  `shuffle` core function randomness distribution and performances

- CHANGELOG.md
- doc/defclass.md
- src/squint/defclass.cljc
- test-resources/defclass_test.cljs
- test/squint/compiler_test.cljs
Issue #492 
---
This change is to add static method and fields to defclass.
Before defclass was only setting fields default values, we now use the ES6 standards of declaring the fields outside the constructor. We have done this in order to declare a static field.
In terms of adding tests, do you prefer I add them to [test-resources/defclass_test.cljs](https://github.com/squint-cljs/squint/blob/e444be0c23137a4fc65638f58d25d0c107c0c8aa/test-resources/defclass_test.cljs) ?
> defclass static methods and fields

- README.md
> Document :output-dir squint.edn option

- examples/vite-react/README.md
This PR closes https://github.com/squint-cljs/squint/issues/549
> Add plugin-react to dev dependencies

- CHANGELOG.md
- resources/squint/core.edn
- src/squint/core.js
- test/squint/compiler_test.cljs
I added some changes to the `take-nth-test` because I tried copying the pattern when doing the tests for `take-last` and they're always successful without the equality check.
> Fix #626: Implement `take-last`

- CHANGELOG.md
- src/squint/string.js
- test/squint/string_test.cljs
> Add `clojure.string` functions `lower-case`, `upper-case`, `capitalize`

- CHANGELOG.md
- examples/ajv/Readme.md
- examples/ajv/ajv.cljs
- examples/ajv/package.json
this PR provides another squint example using AVJ. It arose from a slack thread where I was trying to figure our an error related to a CommonJS module import. 
No  it is an example. (Although it could be run.)
see also: https://clojurians.slack.com/archives/C03U8L2NXNC/p1746459172051509
> add an ajv example

- CHANGELOG.md
- resources/squint/core.edn
- src/squint/core.js
- test/squint/compiler_test.cljs
Closes: https://github.com/squint-cljs/squint/issues/678
> Implement `random-uuid`

- README.md
> doc: further describe warn-on-lazy-reusage!

- README.md
> doc: add cljdoc as a project that uses squint

- README.md
Resubmit for the accidentally closed branch on my previous PR! Apologies for the confusion!
> doc: tip: where to call `warn-on-lazy-reusage!`
