squint-cljs/squint

README.md
Removed a reference to cherry in the readme
=> remove reference of cherry in readme

package.json, src/cherry/compiler.cljc, test/cherry/compiler_test.cljs
Closes #3 
Also, installs shadow-cljs as a dev dependency, and removes the unused branch inside the vector mulimethod impl.
=> Set literal

core.js, src/cherry/compiler.cljc
Related to #7 
Adds the follow functions for working with JS collections immutably:
- `assoc` on objects
- `dissoc` on objects
- `conj` on objects, arrays and sets
- `disj` on sets
Also adds the following mutable JS functions:
- `conj!`
- `disj!`
Also randomly adds `inc` because I wanted to
=> Collection functions

README.md, core.js, src/clava/compiler.cljc, test/clava/compiler_test.cljs
These appear to be significantly faster than the original functions and handle more corner cases in order to more closely match clojure's conj/assoc functions.
**EDIT**: I added get + assoc-in + assoc-in! as a bonus on this PR, and sped up str / added tests for it.
=> Optimizing conj and assoc and making their behavior match clj's more closely

test/clava/compiler_test.cljs
https://github.com/clavascript/clavascript/issues/11#issuecomment-1215398900
**NOTE**: The PR template has a checkbox for updating the changelog (although it's in an html comment), something which this repo doesn't have.
=> Added another test to show that we get new objects when using assoc-in

core.js, resources/clava/core.edn, test/clava/compiler_test.cljs
PR for implementing the JS iterable protocol as an actual Clava protocol that can be extended to Clava types, addressing #125
=> Iterable protocol

core.js, test/clava/compiler_test.cljs
---
`in` doesn't work on numbers and string primitives, so just use property access. #128 related.
This still doesn't support `nil`, which I will create another issue for.
=> satisfies? works on number and string

core.js, transducers.js
=> Transducer protocol

core.js, test/clava/compiler_test.cljs
Fix #162
take would consume one more element in the lazy iterable passed to it than it should
=> take is too eager

core.js, index.html, package.json
This PR speeds up reduce performance for large iterable inputs.
With this PR:
```
$ ./node_cli.js -e '(let [nums (vec (range 100000000))] (time (prn (reduce + nums))))'
4999999950000000
"Elapsed time: 943.758708 msecs"
```
With the previous version this took about 3x as long.
=> reduce performance

src/squint/compiler.cljc
=> Fix ns split on clj

examples/ink/example.cljs, package.json
In React, the [useEffect](https://reactjs.org/docs/hooks-effect.html) hook accepts a list of dependencies as its second argument. When this argument is an empty array, the useEffect hook has no dependencies and runs only once, when the React component mounts.
To re-run the hook every time, we can simply omit the second argument.
I also added `ink` as a dev dependency in the root `package.json`.
=> Add ink in devDependencies and fix example

src/squint/internal/macros.cljc, test/squint/compiler_test.cljs
---
Implements `doseq` in terms of JavaScript `for (let ... of ...) { ... }`, fixing #227 and making the macro overall squint-friendly (no longer emits `unchecked_int` and other vars that don't exist).
=> doseq impl & tests

src/squint/internal/macros.cljc
This PR simplifies the internals of `doseq` as merged in #293. I had riffed off of the old implementation, and it had a lot of code that wasn't necessary.
=> simplify doseq internals

deps.edn, src/squint/compiler/node.cljs, src/squint/internal/cli.cljs
Fixed #301 
Still missing is the ability for squint to recursively watch a folder of cljs files and output them to a matching folder prepended by the output-dir (which I think is needed for bigger projects), but this is still a step in the right direction IMO.
Let me know if you want any tests or more error handling, I couldn't see any existing tests for the cli and tbh am not sure what they should look like
=> Add a simple output-dir option to the cli

CHANGELOG.md, resources/squint/core.edn, src/squint/core.js, test/squint/compiler_test.cljs
As suggested in #418.
It's a straight port of `clojure.core/reductions`.
=> Adding `reductions`

CHANGELOG.md, src/squint/set.js, test/squint/compiler_test.cljs
I amended the PR with two more functions. For map-invert I run into that `reduce-kv` does not handle `Map`s. Should I try to fix it, or do you want to do that, @borkdude?
=> Add `clojure.set` functions`rename`, `project`, and `map-invert`

CHANGELOG.md, src/squint/set.js, test/squint/compiler_test.cljs
Straight port again, except since no TC39 yet, I'm using `core.group-by` instead of `set/index`.
=> Add `clojure.set/join`

CHANGELOG.md, src/squint/set.js, test/squint/compiler_test.cljs
As previously discussed, ported the optimization of doing union and intersection onto the largest set first from ClojureScript's `clojure.set`.
I don't know how to test that it actually is moving the largest set to the top other than testing the utility function itself and exported a special named version of it for this purpose. WDYT?
=> Bubble max set first for `union` and `intersection`

index.html
This PR solves issue #447 by moving some inline styles of the Squint playground into a style tag, and adding media queries for a better layout on mobile. I assume this change does not require a test or changelog addition.
---
=> Add mobile-friendly CSS to playground

src/squint/compiler_common.cljc, test/squint/compiler_test.cljs
Considering that squint tries to provide direct bindings to the JS platform, I thought supporting the [Null Coalescing Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) could be useful. I'm finding it useful.
=> Add js-??, null coalescing operator

examples/game-of-life/package.json, examples/vite-react/package.json, package.json
on v4 chokidar reduced it's dependencies from 13 to 1.
this reduces the dependency tree of squint-cljs quite a lot.
I've been using this version in a project with an override for a week now and everything seems to work.
from the [changelog](https://github.com/paulmillr/chokidar?tab=readme-ov-file#upgrading) looks like there is nothing to be changed.
=> update chokidar to 4.0.1

.clj-kondo/http-kit/http-kit/config.edn, .clj-kondo/http-kit/http-kit/httpkit/with_channel.clj, .clj-kondo/rewrite-clj/rewrite-clj/config.edn, .clj-kondo/taoensso/encore/config.edn, .clj-kondo/taoensso/encore/taoensso/encore.clj, CHANGELOG.md, package.json, src/squint/internal/cli.cljs
Fix watcher & compiler not overriding `squint.edn` configurations with command line options.
---
=> fix: overrides config with cli options

CHANGELOG.md, src/squint/core.js, test/squint/compiler_test.cljs
This resolves issue #607, so that `mapcat` will return a transducer in case no collections are provided:
```clj
(def predicate-keyword-id-map (into {}
(mapcat (fn [[keyword ids]]
(map (fn [id] [id keyword]) ids)))
predicate-id-keyword-map))
```
=> Make mapcat be a transducer if no collections are provided

CHANGELOG.md, resources/squint/core.edn, src/squint/core.js, test/squint/compiler_test.cljs
This PR implements the function `set?` to fix issue #611 .
=> Implement the `set?` function

CHANGELOG.md, src/squint/compiler_common.cljc, test/squint/compiler_test.cljs
This fixes issue #640 by not emitting JavaScript code for anonymous functions that are statements.
=> Fix issue #640: don't emit anonymous function if it is a statement

CHANGELOG.md, src/squint/core.js, test/squint/compiler_test.cljs
This issue fixes issue #643 to support lexicographic `compare` of arrays, which is useful with `sort-by`.
=> Fix issue #643: Support lexicographic compare of arrays

bb/tasks.clj
This seems to work fine on CI, but when `bb test:node` is run locally, the dummy invocation of `npx` brings up an interactive terminal.
=> test:node: remove dummy invocation of npx
